version : '3'
services:
  db:
    container_name: mto-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  server:
    container_name: mto-server
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://root:root@db/mto_db
      - DATABASE_MIN_CONNS=1
      - DATABASE_MAX_CONNS=100
      - DATABASE_CONN_TIMEOUT=10 # secs
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    depends_on:
      db:
        condition: service_healthy